import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import HappyClient from '../components/HappyClient'
import ContentstackProfile from '../components/ContentstackProfile'
import WhyChoose from '../components/WhyChoose';
import UserAndDev from '../components/UserAndDev'
import Integration from '../components/Integration'
import Care from '../components/Care';
import Partners from '../components/Partners'
import Alliance from '../components/Alliance'
import Resources from '../components/Resources'
import TryBelieve from '../components/TryBelieve';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Content Stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <HappyClient />
      <ContentstackProfile />
      <WhyChoose />
      <UserAndDev />
      <Integration />
      <Care />
      <Partners />
      <Alliance />
      <Resources />
      <TryBelieve />
    </div>
  )
}
